# REIT STOCK ANALYSIS

In this project, you will analyze Real Estate Investment Trusts, commonly known as REITs. REITs are companies that own or operate real estate that produces income. REITs, like the stocks of regular public companies, are traded on different stock exchanges. Investing in a REIT allows you to invest in portfolios of real estate assets the same way you can invest in a company by buying its stock.

Using financial statistics and NumPy you will analyze two REITs: [Sabra Health Care REIT Inc. (NASDAQ: SBRA)](https://finance.yahoo.com/quote/SBRA/), which invests in health care real estate, and [Equity Residential (NASDAQ:EQR)](https://finance.yahoo.com/quote/EQR/), which invests in rental apartment properties.

The time period for analysis we will be using is `Jan 1 2018` to `Dec 31 2018`. The REIT data for SBRA (`SBRA.csv`) and EQR (`EQR.csv`) can be found in the same folder as this file.

1. Import the numpy module as np

In [1]:
import numpy as np
import pandas as pd

2. Load the adjusted closings for SBRA

In [2]:
sbra = pd.read_csv('SBRA.csv')
adj_closings_sbra = list(sbra['Adj Close'])

3. Load the adjusted closings for EQR

In [3]:
eqr = pd.read_csv('EQR.csv')
adj_closings_eqr = list(eqr['Adj Close'])

## Simple Rate of Return Function

4. To calculate the daily rate of return for the SBRA stock, we need the daily adjusted closing price. The formula we are using for the daily rate of return is `out[n] = a[n+1] - a[n]`

5. Create a function that returns the daily rate of return

    step 1. define a function named `rate_of_return`
    
    step 2. create parameter for  `adj_closings`
    
    step 3. Within the function use np.diff() and set it to the variable `daily_simple_ror`
    
    step 4. return `daily_simple_ror`

In [4]:
def rate_of_return(adj_closings):
    daily_simple_ror = np.diff(adj_closings)
    return daily_simple_ror

## Calculate Daily Rate of Return for SBRA

6. Call the function `simple_rate_of_return` with the arguments `adj_closings_sbra`. Then print the results. 

In [5]:
daily_simple_returns_sbra = rate_of_return(adj_closings_sbra)
daily_simple_returns_sbra

array([ 0.650056,  0.51622 ,  0.353707,  0.544899,  0.095596, -0.00956 ,
       -0.086036, -0.162514,  0.152954,  0.430184,  0.258111,  0.238991,
       -0.03824 ,  0.191194,  0.277228,  0.31547 ,  0.296346, -0.009558,
        0.181632,  0.076479, -0.210312,  0.23899 , -0.124275,  0.095597,
        0.172071, -0.152954, -0.047796, -0.248553, -0.028677,  0.009777,
        0.205321, -0.156435, -0.146658, -0.019556, -0.078217, -0.508417,
       -0.254208, -0.342201, -0.322649, -0.400867, -0.068442,  0.009779,
       -0.107549, -0.029332, -0.048887,  0.312872,  0.224877,  0.332426,
        0.029329, -0.078217, -0.166214,  0.039111,  0.215099,  0.606188,
       -0.293318,  0.156437,  0.312872,  0.107548,  0.322649, -0.156437,
       -0.136879, -0.019556, -0.185767,  0.068442,  0.195543, -0.087995,
       -0.06844 ,  0.244431,  0.195545,  0.      , -0.019556, -0.400866,
       -0.45953 ,  0.351981, -0.303095,  0.303095,  0.195545,  0.      ,
        0.24443 , -0.185768,  0.156435, -0.029329, 

## Calculate Daily Rate of Return for EQR

7. Call the function `simple_rate_of_return` with the arguments `adj_closings_eqr`. Then print the results. 

In [6]:
daily_simple_returns_eqr = rate_of_return(adj_closings_eqr)
daily_simple_returns_eqr

array([ 0.393986,  0.393982,  0.531872,  1.201652,  0.      ,  1.073601,
        0.137886,  0.078797,  0.817505,  0.610679,  0.817513,  0.20684 ,
        0.275788, -0.059105,  0.009857,  0.315178,  1.03421 ,  0.640221,
       -0.364441,  0.551574, -0.531868,  0.758416,  0.157585,  0.049247,
        0.531884, -0.098496,  0.019692, -0.906151,  0.738708, -0.167434,
        0.088638,  0.315186, -0.837204,  1.162246,  0.364434, -0.719025,
        0.21669 , -0.384125,  0.354584, -0.187149,  0.472786, -0.049256,
       -0.374275, -0.118194,  0.206833,  0.787971,  0.600815, -0.137886,
        0.147735, -0.295478, -0.768265, -0.472786,  0.118202,  1.15239 ,
        0.176666,  0.069473,  0.664971, -0.158799,  0.645119, -0.307671,
       -0.337448,  0.704674, -0.297752, -0.109177,  0.327522, -0.049621,
       -0.168724,  0.952789,  0.337448,  0.754295,  0.148873, -1.855957,
       -1.429192,  0.774147, -0.893249,  0.784073,  0.506172,  0.496246,
        0.228272, -0.893242,  1.111587,  0.099251, 

## Calculate Average Daily Return for SBRA

8. Use `np.mean()` with the argument `daily_simple_returns_sbra` to calculate the average daily return for SBRA. Then set it to the variable name `average_daily_simple_return_sbra`

In [7]:
average_daily_simple_return_sbra = np.mean(daily_simple_returns_sbra)
average_daily_simple_return_sbra

0.03518431707317077

## Calculate Average Daily Return for EQR

9. Use `np.mean()` with the argument `daily_simple_returns_eqr` to calculate the average daily return for EQR. Then set it to the variable name `average_daily_simple_return_eqr`

In [8]:
average_daily_simple_return_eqr = np.mean(daily_simple_returns_eqr)
average_daily_simple_return_eqr

0.10666117073170725

## Compare the Average Daily Return between EQR and SBRA

10. Based on the average daily simple returns of EQR and SBRA, which stock is more likely to be profitable in the future?

**A**: The average daily simple return of EQR is higher than SBRA, it is more likely that EQR will be profitable in the future.

## Daily Log Returns Function

11. Create a function that returns the daily rate of return

    step 1. define a function named log_returns
    
    step 2. create parameter for  `adj_closings`
    
    step 3. use np.log() to get the log of each adjusted closing price and set it to the variable `log_adj_closings`
    
    step 4. use np.diff() to get the diff of each daily log adjusted closing price and set it to the variable `daily_log_returns`
    
    step 5. return `daily_log_returns`

In [9]:
def log_returns(adj_closings):
    log_adj_closings = np.log(adj_closings)
    daily_log_returns = np.diff(log_adj_closings)
    return daily_log_returns

## Calculate Daily Log Returns for SBRA

12. Call the function `log_returns` with the arguments `adj_closings_sbra`. Set it to the variable `daily_log_returns_sbra`. Then print the results. 

In [10]:
daily_log_returns_sbra = log_returns(adj_closings_sbra)
daily_log_returns_sbra

array([ 0.04144414,  0.03173003,  0.02117393,  0.03176639,  0.00547045,
       -0.00054572, -0.00492473, -0.00936905,  0.00882034,  0.02439809,
        0.01435818,  0.01311323, -0.00208667,  0.01038978,  0.01487581,
        0.01666295,  0.01540389, -0.00049313,  0.00932975,  0.00390254,
       -0.01076858,  0.01222804, -0.00633993,  0.00488047,  0.00872509,
       -0.00775197, -0.00243476, -0.01275791, -0.00148248,  0.00050568,
        0.01056078, -0.00803617, -0.00759303, -0.00101686, -0.00407743,
       -0.0269168 , -0.01373503, -0.01879239, -0.0180481 , -0.02288689,
       -0.00396048,  0.00056684, -0.00625177, -0.00171186, -0.00285965,
        0.01816172,  0.01285297,  0.01870243,  0.00163339, -0.00436201,
       -0.0093331 ,  0.00220398,  0.01203516,  0.03315811, -0.01590708,
        0.00851529,  0.01681599,  0.00571571,  0.01695394, -0.00818426,
       -0.00721641, -0.00103528, -0.00988817,  0.00365448,  0.01036808,
       -0.00465237, -0.0036335 ,  0.01291675,  0.01021462,  0.  

## Calculate Daily Log Returns for EQR

13. Call the function `log_returns` with the arguments `adj_closings_eqr`. Set it to the variable `daily_log_returns_eqr`. Then print the results. 

In [11]:
daily_log_returns_eqr = log_returns(adj_closings_eqr)
daily_log_returns_eqr

array([ 0.006254  ,  0.00621507,  0.00832947,  0.01856708,  0.        ,
        0.01630188,  0.00207458,  0.00118362,  0.01219786,  0.00901573,
        0.01194346,  0.00299935,  0.00398522, -0.00085275,  0.00014226,
        0.00453827,  0.01474861,  0.00902221, -0.00512584,  0.00774768,
       -0.00746985,  0.01063474,  0.00219559,  0.00068516,  0.00737016,
       -0.00136074,  0.0002722 , -0.01260281,  0.01028593, -0.00232213,
        0.00122999,  0.00436147, -0.01162714,  0.01610517,  0.00499698,
       -0.00988309,  0.00298873, -0.00530423,  0.00489731, -0.0025818 ,
        0.00650949, -0.0006762 , -0.00515315, -0.00163287,  0.00285568,
        0.01080518,  0.00816103, -0.00186706,  0.00200029, -0.0040047 ,
       -0.01048821, -0.00650949,  0.00163143,  0.01576737,  0.00239537,
        0.0009404 ,  0.0089567 , -0.00213163,  0.00863161, -0.00410731,
       -0.0045243 ,  0.0094247 , -0.00397147, -0.00146018,  0.00437405,
       -0.00066146, -0.00225241,  0.01265335,  0.0044433 ,  0.00

## Annualize Daily Log Return Function

14. Create a function that annualizes the daily rate of return

    step 1. define a function named `annualize_log_return`
    
    step 2. create parameter for  `daily_log_returns`
    
    step 3. use `np.mean()` with the argument `daily_log_returns` to calculate the average daily return. Then set it to the variable name `average_daily_log_returns`
    
    step 4. then multiply `average_daily_log_returns` by 250 and set it to the variable `annualized_log_return`
    
    step 5. return `annualized_log_return`

In [12]:
def annualize_log_return(daily_log_returns, multiplication_factor=250):
    average_daily_log_returns = np.mean(daily_log_returns)
    annualized_log_return = multiplication_factor * average_daily_log_returns
    return annualized_log_return

## Calculate Annualize Daily Log Return for SBRA

10. Call the function `annualize_log_return` with the arguments `daily_log_returns_sbra`. Set it to the variable `annualized_log_return_sbra`. Then print the results. 

In [13]:
annualized_log_return_sbra = annualize_log_return(daily_log_returns_sbra)
annualized_log_return_sbra

0.5044563709645342

## Calculate Annualize Daily Log Return for EQR

11. Call the function `annualize_log_return` with the arguments `daily_log_returns_eqr`. Set it to the variable `annualized_log_return_eqr`. Then print the results. 

In [14]:
annualized_log_return_eqr = annualize_log_return(daily_log_returns_eqr)
annualized_log_return_eqr

0.3855982155640554

## Compare the Annualize Daily Log Return between EQR and SBRA

12. Based on the differences between the Annualize Daily Log Return for EQR and SBRA, Which could be more profitable in the future and why?

SBRA has the higher annualized log return, therefore SBRA might be mor profitable in the future.

## Calculate Variance of Daily Log Return for SBRA

13. Calculate the variance of the daily logarithmetic return for SBRA. Use the function `np.var()` with the argument `daily_log_returns_sbra`. Set it to the variable `daily_variance_sbra`. Then print the results. 

In [15]:
daily_varaince_sbra = np.var(daily_log_returns_sbra)
daily_varaince_sbra

0.00017844226355047114

## Calculate Variance of Daily Log Return for EQR

14. Calculate the variance of the daily logarithmetic return for EQR. Use the function `.var()` with the argument `daily_log_returns_eqr`. Set it to the variable `daily_varaince_eqr`. Then print the results. 

In [16]:
daily_varaince_eqr = np.var(daily_log_returns_eqr)
daily_varaince_eqr

6.833881310511549e-05

## Compare the Variance of Daily Log Return between EQR and SBRA

15. Explain which investment is more riskier based on the Variance of daily log return between EQR and SBRA ?

The variance of SBRA is higher than EQR, therefore SBRA is the more riskier investment.

## Calculate the Daily Standard Deviation for SBRA

16. Calculate the Standard Deviation of the daily logarithmetic return for SBRA. Use the function `np.std()` with the argument `daily_log_returns_sbra`. Set it to the variable `daily_sd_sbra`. Then print the results. 

In [17]:
daily_sd_sbra = np.std(daily_log_returns_sbra)
daily_sd_sbra

0.013358228308816673

## Calculate the Daily Standard Deviation for EQR

17. Calculate the Standard Deviation of the daily logarithmetic return for EQR. Use the function `np.std()` with the argument `daily_log_returns_eqr`. Set it to the variable `daily_sd_eqr`. Then print the results. 

In [18]:
daily_sd_eqr = np.std(daily_log_returns_eqr)
daily_sd_eqr

0.008266729287034594

## Compare the Daily Standard Deviation between EQR and SBRA

18. Has your previous variance risk assessment changed based on the Daily Standard Deviation and why?

No, it did not change, SBRA has a higher standard deviation than EQR.

## Calculate the Correlation between SBRA and EQR

19. Calculate the Correlation of the daily logarithmetic return between SBRA and ERQ assets. Use the function `np.corrcoef()` with the arguments `daily_log_returns_sbra` and `daily_log_returns_eqr`. Set it to the variable `corr_sbra_eqr`. Then print the results. 

In [19]:
print(np.corrcoef(daily_log_returns_sbra, daily_log_returns_eqr))

[[1.         0.62096591]
 [0.62096591 1.        ]]


## Interpret the Correlation between SBRA and EQR

20. Interpret and explain the correlation between the stocks SBRA and EQR?

The correlation between SBRA and EQR is positive. SBRA invests in health care real estates and EQR invests in retnal apartment properties. There seems to be a correlation between the profit of these two industries.

## Final Analysis

21. Which stock would you invest in based on risk and profitability?

SBRA has a higher standard deviation with a higher rate of return. Based on the risk appetite the investment should be chosen.